# Site
title:              MIRU.CH
bio:                'Michael Rueefli is one of the ‘make it noble’ partners, supporting clients and partners in training, concepts, designs and implementations around Microsoft Azure and DevOps.As a long-standing Microsoft MVP, he supports communities worldwide with his Microsoft Azure and Data Center know-how. He is a regular speaker at international events and conferences. He also shares his knowledge on his private blog: www.miru.ch'
description:        "A blog about cloud & datacenter"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Comments
disqus_shortname:   "drmiru"

# Social
analytics-id:       "default"
twitter:            drmiru
facebook:           drmiru
instagram:          michael.rueefli
github:             drmiru

# personal
location:           Switzerland
phone:              ask me
email:              drmiru@hotmail.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bgblue.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    comments: true
    author: "Michael Rueefli"

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

jekyll-archives:
  enabled:
    - year
    - month
    - tags
    - categories
  layout: 'page'
  layouts:
    year: year
    month: month
    tag: tag_and_category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  #- jekyll-archives
 

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
